# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]

alt-n = 'focus left'
alt-e = 'focus down'
alt-i = 'focus up'
alt-o = 'focus right'

alt-shift-n = 'move left'
alt-shift-e = 'move down'
alt-shift-i = 'move up'
alt-shift-o = 'move right'

alt-m = ['join-with left', 'mode main']
alt-comma = ['join-with down', 'mode main']
alt-period = ['join-with up', 'mode main']
alt-slash = ['join-with right', 'mode main']

alt-l = 'fullscreen'
alt-u = 'layout v_accordion'
alt-y = 'layout tiles horizontal vertical'
alt-semicolon = 'layout floating tiling'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-minus = 'workspace 11'
alt-equal = 'workspace 12'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-minus = 'move-node-to-workspace 11'
alt-shift-equal = 'move-node-to-workspace 12'

ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'
