# taps
tap 'homebrew/cask-fonts'
# specify a directory to install
cask_args appdir: '/Applications'
# install packages
brew 'awscli'
brew 'git'
brew 'htop'
brew 'minikube'
brew 'python'
brew 'tmux'
brew 'vim'
# install applications
cask 'alfred'
cask 'dashlane'
cask 'docker'
cask 'dotnet-sdk'
cask 'dozer'
cask 'firefox'
cask 'font-fira-code'
cask 'font-jetbrains-mono'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'postman'
cask 'rectangle'
cask 'spotify'
cask 'visual-studio-code'
